baseURL: https://guozheng.netlify.app/
languageCode: zh-CN
title: Residualsun | 黄国政
theme: "hugo-theme-mini"
buildFuture: true
timeZone: "Etc/GMT-8"    # UTC+08:00 timezone

# Default content language, support en (English) / zh (Chinese) / nl (Dutch) / fr (French) / es (Spanish) / da (Danish), default 'en'
defaultContentLanguage: zh

preserveTaxonomyNames: true

# !!! exampleSite only, you may need to delete the line: `themesDir: ../../` 

hasCJKLanguage: true
permalinks:
  posts: /posts/:year/:month/:slug/

paginate: 9
enableGitInfo: true      # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。

#googleAnalytics: your-google-analytics-id
#disqusShortname: https-guozheng-netlify-app

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  # github: https://github.com/residualsun1
  # twitter: your-github-link
  # stackoverflow: your-github-link
  # facebook: your-facebook-link


# Site parameters
params:
  # Site Author
  author: 残日留痕
  # Author biography
  bio: 放下执念
  # Site Description, used in HTML meat
  description: My Blog

  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: true
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: true
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: '' 

  # Extra links in navigation
  links:
    ## e.g.
    # - name: Project
    #   path: /project
    - name: 社会学-人类学
      path: /sociology_anthropology/
    - name: 我与R
      path: /r_and_i/
      
  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js
